name: Build Clang for musl (no sysroot)
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install tools
        run: |
         sudo apt-get install -y ninja-build mingw-w64
        shell: bash
      - name: Build
        run: |
         sudo chmod +x ./build.sh
         sudo cp afunix.h /usr/x86_64-w64-mingw32/include
         sudo ./build.sh
        shell: bash
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: clang
          path: /home/clang.zip