# This is a basic workflow to help you get started with Actions

name: Build Clang for musl (no sysroot)

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell.
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.14
      - name: Install tools
        run: |
         sudo apt-get install -y clang ninja-build mingw-w64
        shell: bash
      - name: Build and Upload
        env:
              GH_TOKEN: ${{ github.token }}
        run: |
         sudo chmod +x ./build.sh
         sudo ./build.sh
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: clang
          path: /home/clang.zip
