name: Build Clang for musl (no sysroot)
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.14
      - name: Install tools
        run: |
         sudo apt-get install -y clang ninja-build
        shell: bash
      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
            platform: x64
      - name: Build
        run: |
         sudo chmod +x ./build.sh
         sudo cp afunix.h /usr/x86_64-w64-mingw32/include
         sudo ./build.sh
        shell: bash
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: clang
          path: /home/clang.zip