
name: Build Clang for musl (no sysroot)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.14
      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
            platform: x64
      - name: Build
        run: |
         x86_64-w64-mingw32-gcc-posix thread.c -o thread
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: test binary
          path: /home/thread.exe
