
name: Test workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.14
      - name: Build
        run: |
         sudo apt-get install -y mingw-w64
         x86_64-w64-mingw32-gcc-posix thread.c -o thread.exe
         sudo cp thread.exe /home
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: test binary
          path: /home/thread.exe
